# Generated by Django 4.2.3 on 2023-07-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, unique=True)),
                ('email', models.CharField(max_length=20)),
                ('desig', models.CharField(max_length=30)),
                ('salary', models.IntegerField(default=0)),
                ('exp', models.IntegerField(max_length=2)),
                ('skill', models.CharField(max_length=20)),
                ('aow', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=12)),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=40)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.role')),
            ],
        ),
    ]
