# Generated by Django 4.2.3 on 2023-07-14 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
