# Generated by Django 4.2.3 on 2023-07-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_employee_aow_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
